<?php /* @var $this PressLoft_Affiliate_Block_Affiliate */ ?>

<script>
    document.observe("dom:loaded", function() {

        let setAffiliateCookieUrl = "<?= $this->getExpiresCookieUrl() ?>";
        const urlParams = new URLSearchParams(window.location.search);

        if (urlParams) {
            const tokenName ='<?= $this->getTokenName() ?>';
            const tokenValue = urlParams.get(tokenName);
            if (tokenValue) {
                new Ajax.Request(setAffiliateCookieUrl, {
                    evalScripts: true,
                    parameters: {
                        pltoken: tokenValue
                    },
                    onSuccess: function(transport) {
                        let responseText = transport.responseText.replace(/>\s+</g, '><');

                        if (transport.responseText.isJSON()) {
                            let response = transport.responseText.evalJSON()
                            console.log(response.message);
                        }
                    },
                    onerror: function (transport) {
                        console.log(transport.responseText.replace(/>\s+</g, '><'));
                    }
                });
            }
        }
    });
</script>
